config/routes.rb
Rails.application.routes.draw do

  post 'testpdf' => 'visitors#testpdf', as: 'testpdf'
  get 'testpdf_cover' => 'visitors#testpdf_cover', as: 'testpdf_cover'
  get 'testpdf_header' => 'visitors#testpdf_header', as: 'testpdf_header'
  get 'testpdf_footer' => 'visitors#testpdf_footer', as: 'testpdf_footer'

  root to: 'visitors#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

  def testpdf
    options = {
      :filename => params[:filename],
      :engine => params[:engine],
      'orientation' => params[:orientation],
      'margin-top' => params[:top],
      'margin-bottom' => params[:bottom],
      'margin-right' => params[:right],
      'margin-left' => params[:left]
    }
    options['cover'] = testpdf_cover_url if params[:cover].present?
    options['header'] = testpdf_header_url if params[:header].present?
    options['footer'] = testpdf_footer_url if params[:footer].present?
    render_pdf_from root_url, options
  end

  # only for wkhtmltopdf
  def testpdf_cover
    render 'visitors/pdf/cover', layout: false
  end

  # only for wkhtmltopdf
  def testpdf_header
    render 'visitors/pdf/header', layout: false
  end

  # only for wkhtmltopdf
  def testpdf_footer
    render 'visitors/pdf/footer', layout: false
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Url2pdf Testrailsapp'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Url2pdf Testrailsapp'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield

app/views/visitors/index.html.haml
.row.well
  %h1
    PDF Options
= form_tag testpdf_path do
  .row.well
    .col-xs-12.col-md-3
      %label
        %h4 Orientation
      .radio
        %label
          %input{type: 'radio', name: 'orientation', value: 'portrait', checked: true}
          Portrait
        %label
          %input{type: 'radio', name: 'orientation', value: 'landscape', checked: false}
          Landscape
    .col-xs-12.col-md-9
      %label
        %h4 Cover, header and footer
      .checkbox
        %label
          = check_box_tag 'cover', 1, true
          Include cover sheet
          = link_to '[test cover]', testpdf_cover_url
      .checkbox
        %label
          = check_box_tag 'header', 1, true
          Include header
          = link_to '[test header]', testpdf_header_url
      .checkbox
        %label
          = check_box_tag 'footer', 1, true
          Include footer
          = link_to '[test footer]', testpdf_footer_url
  .row.well
    .col-xs-12
      %label
        %h4 Margins
    .col-xs-12.col-md-3
      %label
        Top
        = text_field_tag 'top', '0mm', class: 'form-control'
    .col-xs-12.col-md-3
      %label
        Right
        = text_field_tag 'right', '10mm', class: 'form-control'
    .col-xs-12.col-md-3
      %label
        Bottom
        = text_field_tag 'bottom', '0mm', class: 'form-control'
    .col-xs-12.col-md-3
      %label
        Left
        = text_field_tag 'left', '10mm', class: 'form-control'
  .row.well
    .col-xs-12.col-md-3
      %label
        %h4 Generation
      .form-group
        %label
          = text_field_tag 'filename', 'test.pdf', class: 'form-control'
    .col-xs-12.col-md-3
      %label
        %h4 Engine
      .radio
        %label
          %input{type: 'radio', name: 'engine', value: 'wkhtmltopdf', checked: true}
          wkhtmltopdf
        %label
          %input{type: 'radio', name: 'engine', value: 'phantomjs', checked: false}
          phantomjs
    .col-xs-12.col-md-3
      %label
      .form-actions
        %button.btn.btn-primary
          Generate PDF

app/views/visitors/pdf/cover.html.haml
%h1
  The Cover sheet

%p
  No headers or footers etc.

app/views/visitors/pdf/footer.html.haml
%h4.pull-right
  My nice footer

app/views/visitors/pdf/header.html.haml
!!!
%html
  %head
  %body
    %p
      My nice header